# Data cleaning techniques and outliers detection

## Outliers and influence measures

**Leverage** given by

$$
h_i = \frac{1}{n} + \frac{(X_i - \overline{X})}{\sum(X_i - \overline{X})^2}
$$

**Studentized residuals** given by

$$
e_{i}^{*}=\frac{e_i}{S_{e(-1)}\sqrt{1-h_i}}
$$

where:
$e_i$ - residual, $S_{e(-1)}$ - standard error of the regression without i-th observation. Studentized residuals follow t-distribution with $n-k-2$ degress of freedom.

**Cook distance**
$$ 
D_i=\frac{e_i}{k+1}\frac{h_i}{1-h_i}
$$

where $k$  -- number of dependent variables, $h_i = \frac{1}{n} + \frac{(X_i - \overline{X})}{\sum(X_i - \overline{X})^2}$ , $MSE=\frac{1}{n}\sum_{i=1}^n(\hat{Y}_i-Y_i)^2$
outliers meet:

$$
D_i>\frac{4}{n-k-1}
$$

**DFBETA** measures change in estimates of regression parameters when we remove one observation

$$
DFBETA_i=(\sum_{i \in s} \mathbf{x}_i\mathbf{x}_i^T)^{-1}\mathbf{x}_i\frac{e_i}{1-\mathbf{x}_i^T(\sum_{i \in s} \mathbf{x}_i\mathbf{x}_i^T)^{-1}\mathbf{x}_i}
$$

**DFBETAS** - standarised version of DFBETA. Measures influence in units of standard error   of regression.

$$ 
DFBETAS_i=\frac{\hat{\mathbf{\beta}}-\hat{\mathbf{\beta}}_{(-i)}}{\sqrt{MSE_{(-i)}}}=\frac{DFBETA_i}{\sqrt{MSE_{(-i)}}}
$$

Outliers meet:

+ $|DFBETAS_i|>2$ - small samples
+ $DFBETAS_i>\frac{2}{\sqrt{n}}$

**DFFITS** -- measures global difference between model with and without *i* observation.

$$
DFFITS_i=\frac{e_i\sqrt{\frac{h_i}{1-h_i}}}{\sqrt{MSE_{(-i)}}\sqrt{{1-h_i}}}
$$

Outliers meet $|DFFITS_i| > 2\sqrt{\frac{p+1}{n-k-1}}$

**CovRatio** -- measures influence on variance of regression coefficients

$$
COVRATIO_i=\frac{1}{(\frac{n-k-2+t_i^2}{n-k-1})^{k+2}}\frac{1}{(1-h_i)}
$$

where $h_i$ is the same as in Cook's distance, $t_i$ is defined

$$
t_i=\frac{e_i}{\sqrt{MSE_{(-i)}}\sqrt{{1-h_i}}}
$$

Interpretation:

+ $COVRATIO_i < 1$ - elimination of $i$ th unit/observation will reduce standard errors of regression coefficients
+ $COVRATIO_i > 1$ - elimination of $i$ th unit/observation will increase standard errors of regression coefficients

it is suggested to use sample size dependent thresholds 

$$
|COVRATIO_i-1| > 3(k+1)/n
$$

