--- 
title: "Real Estate Market Analysis"
author: "Maciej Beręsewicz"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ''
description: "Materials for Real Estate Market Analysis course conducted at Poznań University of Economics and Business"
---

# Prerequisites

Load the required packages

```{r message= FALSE, warning=FALSE}
library(tidyverse) ## data processing and visualsiation
library(zoo) ## parsing quarterly data
library(rvest) ## scraping tools
library(OECD) ## data from OECD
library(eurostat) ## data from eurostat
library(nlme) ## mixed models with nice covariance structures
library(ggmap) ### plot data on maps 
library(quantreg) ### 
library(stringi) ## regular expressions
library(lubridate)
theme_set(theme_bw())
```


# Read the data

```{r}
rema <- read.csv2('datasets/project_data_train.csv', 
                 header = T, 
                 stringsAsFactors = F, 
                 dec ='.')
```

